# Generated by Django 3.2.20 on 2023-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc_collections', '0010_alter_collection_cancer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='program',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
