# Generated by Django 3.2.20 on 2023-11-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_auto_20230531_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='operator',
            field=models.CharField(choices=[('B', '_btw'), ('EB', '_btwe'), ('BE', '_ebtw'), ('EBE', '_ebtwe'), ('GE', '_gte'), ('LE', '_lte'), ('G', '_gt'), ('L', '_lt'), ('A', '_and'), ('O', '_or'), ('E', '_eq')], default='O', max_length=4),
        ),
    ]
